name: Azure Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: innerspacetrainings/azure-npm-publish@master
        with:
          package-dir: 'Assets/Printer'
          npm-email: 'javier.bullrich@innerspace.at'
          organization: 'innerspaceat'
          feed: 'unity-packages'
          username: 'innerspaceat'
          base64-token: ${{ secrets.AZURE_TOKEN }}