name: NPM Publish

on:
  push:
    branches:
      - azure-test

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://pkgs.dev.azure.com/javierbullrich0110/GeneralArtifact/_packaging/My-Registry/npm/registry/
          package: 'Assets/Printer/package.json'
          check-version: false