name: NPM Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: innerspacetrainings/azure-npm-publish@azure-upload
        env:
          REPO: ${{ github.repository }}
        with:
          package-dir: 'Assets/Printer'
          npm-email: 'javier.bullrich@innerspace.at'
          organization: 'javierbullrich0110/GeneralArtifact'
          feed: 'My-Registry'
          username: 'Javyer'
          base64-token: ${{ secrets.AZURE_TOKEN }}