name: Prace.go
on:
  pull_request:
    types: [
      'opened',
      'edited',
      'reopened',
      'synchronize',
      'review_requested',
      'review_request_removed',
      'assigned',
      'unassigned',
      'labeled',
      'unlabeled',
      ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: Bullrich/Prace.js@golang
        with:
          configuration-path: .github/prace.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}